# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0088_auto_20190218_1136'),
        ('motifdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDBMotif',
            fields=[
                ('mass2motif_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicviz.Mass2Motif')),
            ],
            bases=('basicviz.mass2motif',),
        ),
        migrations.AddField(
            model_name='mdbmotifset',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mdbmotifset',
            name='featureset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.BVFeatureSet'),
        ),
        migrations.AddField(
            model_name='mdbmotif',
            name='motif_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motifdb.MDBMotifSet'),
        ),
    ]
