# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0004_mdbmotifset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdbmotifset',
            name='featureset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.BVFeatureSet'),
        ),
    ]
