# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicviz', '0063_mass2motif_linkmotif'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSampleIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='docsampleintensity',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms1analysis.Sample'),
        ),
    ]
