# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms1analysis', '0002_analysis_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[(b'0', b'Pending'), (b'1', b'Ready')], default=b'1', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='group1',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='group2',
            field=models.CharField(max_length=2048),
        ),
    ]
