# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms1analysis', '0003_auto_20170406_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='use_logarithm',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=128, null=True),
        ),
    ]
