# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0064_vizoptions_ms1_analysis_id'),
        ('ms1analysis', '0004_analysis_use_logarithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResultPlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plage', models.FloatField(null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms1analysis.Analysis')),
                ('mass2motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Mass2Motif')),
            ],
        ),
    ]
