# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms1analysis', '0005_analysisresultplage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresultplage',
            old_name='plage',
            new_name='plage_t_value',
        ),
        migrations.AddField(
            model_name='analysisresultplage',
            name='plage_p_value',
            field=models.FloatField(null=True),
        ),
    ]
