# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0018_apibatchresult'),
        ('basicviz', '0065_auto_20170413_1256'),
        ('ms1analysis', '0006_auto_20170413_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecompositionAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('group1', models.CharField(max_length=2048)),
                ('group2', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[(b'0', b'Pending'), (b'1', b'Ready')], default=b'1', max_length=128, null=True)),
                ('use_logarithm', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=128, null=True)),
                ('decomposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decomposition.Decomposition')),
            ],
        ),
        migrations.CreateModel(
            name='DecompositionAnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pValue', models.FloatField(null=True)),
                ('foldChange', models.FloatField(null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms1analysis.DecompositionAnalysis')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Document')),
            ],
        ),
        migrations.CreateModel(
            name='DecompositionAnalysisResultPlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plage_t_value', models.FloatField(null=True)),
                ('plage_p_value', models.FloatField(null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms1analysis.DecompositionAnalysis')),
                ('globalmotif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decomposition.GlobalMotif')),
            ],
        ),
    ]
