# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms1analysis', '0007_decompositionanalysis_decompositionanalysisresult_decompositionanalysisresultplage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
