# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0050_auto_20170221_1147'),
        ('basicviz', '0050_experiment_experiment_type'),
    ]

    operations = [
    ]
