# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0051_merge_20170221_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
