# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:53
from __future__ import unicode_literals

import basicviz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0052_auto_20170221_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='decomposition_source',
            field=models.CharField(choices=[(b'N', b'No'), (b'Y', b'Yes')], default=b'N', max_length=1),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='mzml_file',
            field=models.FileField(blank=True, null=True, upload_to=basicviz.models.get_upload_folder),
        ),
    ]
