# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0054_auto_20170226_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_type',
            field=models.CharField(choices=[(b'0', b'LDA'), (b'1', b'Decomposition')], default=b'0', max_length=128, null=True),
        ),
    ]
