# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0055_auto_20170228_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='duplicate_filter_mz_tol',
            field=models.FloatField(default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='duplicate_filter_rt_tol',
            field=models.FloatField(default=16, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='filter_duplicates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='min_ms1_intensity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
