# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0056_auto_20170302_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='max_ms1_rt',
            field=models.FloatField(default=1260, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='min_ms1_rt',
            field=models.FloatField(default=180, null=True),
        ),
    ]
