# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:38
from __future__ import unicode_literals

import basicviz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0058_experiment_n_its'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='mzml_file',
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_ms2_format',
            field=models.CharField(choices=[(b'0', b'mzML'), (b'1', b'msp')], default=b'0', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='ms2_file',
            field=models.FileField(blank=True, null=True, upload_to=basicviz.models.get_upload_folder),
        ),
    ]
