# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0061_motifmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motifmatch',
            name='tomotif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomotif', to='basicviz.Mass2Motif'),
        ),
    ]
