# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0062_auto_20170405_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass2motif',
            name='linkmotif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.Mass2Motif'),
        ),
    ]
