# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0064_vizoptions_ms1_analysis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizoptions',
            name='colour_by_logfc',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='colour_topic_by_score',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='discrete_colour',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='edge_choice',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='edge_thresh',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='just_annotated_docs',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='lower_colour_perc',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='random_seed',
        ),
        migrations.RemoveField(
            model_name='vizoptions',
            name='upper_colour_perc',
        ),
    ]
