# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0065_auto_20170413_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.Experiment'),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
