# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0066_auto_20170425_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='tasktype',
            field=models.CharField(max_length=1028, null=True),
        ),
    ]
