# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0067_auto_20170425_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experiment_ms2_format',
            field=models.CharField(choices=[(b'0', b'mzML'), (b'1', b'msp'), (b'2', b'mgf')], default=b'0', max_length=128, null=True),
        ),
    ]
