# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0070_experiment_featureset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicExperiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Experiment')),
            ],
        ),
    ]
