# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0071_publicexperiments'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='csv_mz_column',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='csv_rt_column',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='csv_rt_units',
            field=models.CharField(blank=True, choices=[(b'minutes', b'minutes'), (b'seconds', b'seconds')], max_length=128, null=True),
        ),
    ]
