# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-31 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0072_auto_20180831_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='csv_mz_column',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='csv_rt_column',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
