# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0075_remove_experiment_csv_rt_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='csv_id_column',
            field=models.CharField(blank=True, default=b'scans', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='csv_mz_column',
            field=models.CharField(blank=True, default=b'mz', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ms2_id_field',
            field=models.CharField(blank=True, default=b'scans', max_length=128, null=True),
        ),
    ]
