# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0077_auto_20180831_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='ms2_name_field',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_ms2_format',
            field=models.CharField(choices=[(b'0', b'mzML'), (b'1', b'msp'), (b'2', b'mgf'), (b'3', b'upload')], default=b'0', max_length=128, null=True),
        ),
    ]
