# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0079_auto_20181009_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperiment',
            name='mol_string',
            field=models.TextField(null=True),
        ),
    ]
