# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0080_userexperiment_mol_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperiment',
            name='mol_string',
        ),
        migrations.AddField(
            model_name='document',
            name='mol_string',
            field=models.TextField(null=True),
        ),
    ]
