# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0087_experiment_has_magma_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='mass2motif',
            name='id',
        ),
        migrations.AddField(
            model_name='mass2motif',
            name='supermotif_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicviz.SuperMotif'),
            preserve_default=False,
        ),
    ]
