# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0088_auto_20181117_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass2motif',
            name='supermotif_ptr',
        ),
        migrations.AddField(
            model_name='mass2motif',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mass2motif',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.Experiment'),
        ),
        migrations.DeleteModel(
            name='SuperMotif',
        ),
    ]
