# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-06-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0091_auto_20200617_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass2motif',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
