# Generated by Django 3.0.6 on 2021-01-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0092_auto_20200617_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='csv_mz_column',
            field=models.CharField(blank=True, default='mz', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='csv_rt_units',
            field=models.CharField(blank=True, choices=[('minutes', 'minutes'), ('seconds', 'seconds')], default='seconds', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='decomposition_source',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_ms2_format',
            field=models.CharField(choices=[('0', 'mzML'), ('1', 'msp'), ('2', 'mgf'), ('3', 'upload'), ('4', 'uploadgensim')], default='0', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment_type',
            field=models.CharField(choices=[('0', 'LDA'), ('1', 'Decomposition')], default='0', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Ready')], default='1', max_length=128, null=True),
        ),
    ]
