# Generated by Django 3.2.5 on 2021-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0093_auto_20210109_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmass2motif',
            name='validated',
            field=models.BooleanField(null=True),
        ),
    ]
