# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0003_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='feature_id_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beta',
            name='motif_id_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='beta',
            name='beta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='beta',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Experiment', unique=True),
        ),
    ]
