# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0004_auto_20170217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='alpha_list',
            field=models.TextField(null=True),
        ),
    ]
