# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0006_auto_20170217_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentglobalfeature',
            name='intensity',
            field=models.FloatField(null=True),
        ),
    ]
