# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0050_experiment_experiment_type'),
        ('decomposition', '0008_auto_20170220_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFeatureMass2Motif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(null=True)),
                ('Feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decomposition.GlobalFeature')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Document')),
                ('mass2motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decomposition.GlobalMotif')),
            ],
        ),
    ]
