# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0009_documentfeaturemass2motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfeaturemass2motif',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentfeaturemass2motif',
            name='mass2motif',
        ),
        migrations.AddField(
            model_name='documentfeaturemass2motif',
            name='docm2m',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='decomposition.DocumentGlobalMass2Motif'),
            preserve_default=False,
        ),
    ]
