# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0010_auto_20170221_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfeaturemass2motif',
            old_name='Feature',
            new_name='feature',
        ),
    ]
