# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0012_auto_20170228_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomposition',
            name='motifset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decomposition.MotifSet'),
        ),
    ]
