# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0013_auto_20170228_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='beta',
            name='motifset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='decomposition.MotifSet'),
        ),
    ]
