# Generated by Django 3.0.6 on 2021-01-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decomposition', '0018_apibatchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decomposition',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Ready')], default='1', max_length=128, null=True),
        ),
    ]
