# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20161214_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituentinstance',
            name='z_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taxainstance',
            name='z_score',
            field=models.FloatField(null=True),
        ),
    ]
