# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0079_auto_20181009_1105'),
        ('annotation', '0003_auto_20171229_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituentinstance',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='taxainstance',
            name='motif',
        ),
        migrations.AddField(
            model_name='substituentinstance',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.Document'),
        ),
        migrations.AddField(
            model_name='taxainstance',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.Document'),
        ),
    ]
