# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20181112_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substituentinstance',
            name='z_score',
        ),
        migrations.RemoveField(
            model_name='taxainstance',
            name='z_score',
        ),
        migrations.AddField(
            model_name='substituentinstance',
            name='source',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='taxainstance',
            name='source',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
