# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdbmotifset',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
