# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0087_experiment_has_magma_annotation'),
        ('motifdb', '0002_mdbmotifset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdbmotifset',
            name='featureset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicviz.BVFeatureSet'),
        ),
    ]
