# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0002_auto_20190218_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdbmotifset',
            name='metadata',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mdbmotifset',
            name='name',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
