# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0087_experiment_has_magma_annotation'),
        ('motifdb', '0003_mdbmotifset_featureset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDBMotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('motif_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motifdb.MDBMotifSet')),
            ],
        ),
        migrations.CreateModel(
            name='MDBMotifInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicviz.Feature')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motifdb.MDBMotif')),
            ],
        ),
    ]
