# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0004_mdbmotif_mdbmotifinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdbmotifinstance',
            name='probability',
            field=models.FloatField(null=True),
        ),
    ]
