# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0005_auto_20181116_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdbmotifinstance',
            name='annotation',
            field=models.TextField(null=True),
        ),
    ]
