# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0006_mdbmotifinstance_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdbmotifinstance',
            name='annotation',
        ),
        migrations.AddField(
            model_name='mdbmotif',
            name='annotation',
            field=models.TextField(null=True),
        ),
    ]
