# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0007_auto_20181116_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdbmotif',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mdbmotif',
            name='short_annotation',
            field=models.TextField(null=True),
        ),
    ]
