# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicviz', '0089_auto_20181117_0905'),
        ('motifdb', '0008_auto_20181116_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdbmotif',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mdbmotif',
            name='name',
        ),
        migrations.AddField(
            model_name='mdbmotif',
            name='mass2motif_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicviz.Mass2Motif'),
            preserve_default=False,
        ),
    ]
