# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0009_auto_20181117_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdbmotif',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='mdbmotif',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='mdbmotif',
            name='short_annotation',
        ),
    ]
