# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motifdb', '0010_auto_20181117_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdbmotifinstance',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='mdbmotifinstance',
            name='motif',
        ),
        migrations.DeleteModel(
            name='MDBMotifInstance',
        ),
    ]
