# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0003_auto_20171229_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_type', models.CharField(max_length=124)),
                ('classifier', models.TextField()),
                ('feature_index', models.TextField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.SubstituentTerm')),
            ],
        ),
    ]
