# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclassifier',
            name='classifier',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subclassifier',
            name='classifier_type',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='subclassifier',
            name='feature_index',
            field=models.TextField(null=True),
        ),
    ]
